services:
  elasticsearch:
    image: elasticsearch:8.4.3
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - 9200:9200
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: "false"
      node.name: es01
      discovery.type: single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes: 
      - redis_data:/data

  mysql:
    image: mysql:8
    container_name: mysql
    # if client does not support caching_sha2_password
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      # bug - unable to connect form host without bridge network
      - mysql-network
  
  postgres:
    image: postgres:18
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
    volumes:
      - psql18:/var/lib/postgresql
      # directory with sql scripts to populate database
      # - ./psql_init:/docker-entrypoint-initdb.d

volumes:
  esdata:
  redis_data:
  mysql-volume:
  psql18:

networks:
  elastic:
  mysql-network:
    driver: bridge