#!/bin/bash

DATABASE_ENGINE="$1"
DATABASE_ENGINE="${DATABASE_ENGINE:=postgres}"

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "$SCRIPT_DIR/../docker"
pwd

docker-compose -f docker-compose.db.yml up -d $DATABASE_ENGINE
